# Generated by Django 5.1.7 on 2026-02-22 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da categoria', max_length=255, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição da categoria', null=True, verbose_name='Descrição')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição da categoria', verbose_name='Ordem de exibição')),
                ('active', models.BooleanField(default=True, help_text='Indica se a categoria está ativa', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do produto', max_length=255, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição do produto', null=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço do produto', max_digits=10, verbose_name='Preço')),
                ('active', models.BooleanField(default=True, help_text='Indica se o produto está ativo', verbose_name='Ativo')),
                ('highlight', models.BooleanField(default=False, help_text='Indica se o produto é destaque', verbose_name='Destaque')),
                ('category', models.ForeignKey(help_text='Categoria do produto', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ProductExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do extra do produto', max_length=255, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço do extra do produto', max_digits=10, verbose_name='Preço')),
                ('active', models.BooleanField(default=True, help_text='Indica se o extra do produto está ativo', verbose_name='Ativo')),
                ('product', models.OneToOneField(help_text='Produto ao qual este extra pertence', on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='core.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Extra do Produto',
                'verbose_name_plural': 'Extras dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='ProductOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do grupo de opções', max_length=255, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição do grupo de opções', null=True, verbose_name='Descrição')),
                ('mandatory', models.BooleanField(default=False, help_text='Indica se a seleção de uma opção deste grupo é obrigatória', verbose_name='Obrigatório')),
                ('multiple_choice', models.BooleanField(default=False, help_text='Indica se é permitido selecionar múltiplas opções deste grupo', verbose_name='Múltipla escolha')),
                ('product', models.ForeignKey(help_text='Produto ao qual este grupo de opções pertence', on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='core.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Grupo de Opções',
                'verbose_name_plural': 'Grupos de Opções',
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da opção', max_length=255, verbose_name='Nome')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço adicional para esta opção', max_digits=10, verbose_name='Preço adicional')),
                ('active', models.BooleanField(default=True, help_text='Indica se a opção está ativa', verbose_name='Ativo')),
                ('option_group', models.ForeignKey(help_text='Grupo de opções ao qual esta opção pertence', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.productoptiongroup', verbose_name='Grupo de opções')),
            ],
            options={
                'verbose_name': 'Opção de Produto',
                'verbose_name_plural': 'Opções de Produto',
            },
        ),
    ]
