# Generated by Django 5.1.7 on 2026-02-22 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_product_productextra_productoptiongroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin', models.CharField(choices=[('SITE', 'Site')], default='SITE', max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=20)),
                ('delivery_type', models.CharField(choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Retirada')], max_length=20)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method', models.CharField(choices=[('PIX', 'Pix'), ('CASH', 'Dinheiro'), ('CARD', 'Cartão')], max_length=20)),
                ('change_for', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('GENERATED', 'Gerado'), ('WHATSAPP_OPENED', 'WhatsApp Aberto')], default='GENERATED', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('base_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_item_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.orderintent')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='core.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_group_name', models.CharField(max_length=255)),
                ('option_name', models.CharField(max_length=255)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.orderitem')),
            ],
        ),
    ]
