# Generated by Django 5.1.7 on 2026-02-22 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderintent_orderitem_orderitemextra_orderitemoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da promoção', max_length=255, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição da promoção', null=True, verbose_name='Descrição')),
                ('date_start', models.DateTimeField(help_text='Data e hora de início da promoção', verbose_name='Data de início')),
                ('date_end', models.DateTimeField(help_text='Data e hora de término da promoção', verbose_name='Data de término')),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
            },
        ),
        migrations.AlterModelOptions(
            name='orderintent',
            options={'verbose_name': 'Intenção de Pedido', 'verbose_name_plural': 'Intenções de Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Itens de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='orderitemextra',
            options={'verbose_name': 'Extra do Item de Pedido', 'verbose_name_plural': 'Extras dos Itens de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='orderitemoption',
            options={'verbose_name': 'Opção do Item de Pedido', 'verbose_name_plural': 'Opções dos Itens de Pedido'},
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Porcentagem de desconto aplicada ao produto nesta promoção', max_digits=5, verbose_name='Desconto (%)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_promotions', to='core.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_products', to='core.promotion')),
            ],
            options={
                'verbose_name': 'Produto da Promoção',
                'verbose_name_plural': 'Produtos das Promoções',
            },
        ),
    ]
